apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth-server
  template:
    metadata:
      labels:
        app: eth-server
    spec:
      containers:
        - name: backend
          image: schadokar/eth-server:1.0.0
          resources:
            limits:
              cpu: "250m"
              memory: "500Mi"
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
