apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth-ganache
  template:
    metadata:
      labels:
        app: eth-ganache
    spec:
      containers:
        - name: ganache
          image: schadokar/eth-ganache:1.0.0
          resources:
            limits:
              cpu: "250m"
              memory: "500Mi"
          ports:
            - containerPort: 8545
